export const CALENDAR_DAY_HEADER_HEIGHT = 64;
export const CALENDAR_TASK_LAYER_TOP = 76;
export const CALENDAR_TASK_ROW_HEIGHT = 37;
export const CALENDAR_TASK_FOOTER_PADDING = 18;
export const CALENDAR_MIN_CELL_HEIGHT = 236;
